In [1]:
from Cleaner import *
from config import db_password

## Create the DataFrame

### Player Awards
Up-To-Date data from [Sean Lahman](https://www.seanlahman.com/baseball-archive/statistics/)

In [2]:
awards = pd.read_csv('Resources/AwardsPlayers.csv').drop(columns=['tie','notes'])
all_awards = reverseLookup(awards)

all_awards.loc[all_awards['awardID']=='Most Valuable Player'].sort_values(by = ['yearID']).tail(11)

Gathering player lookup table. This may take a moment.

,Name,mlb_played_first,mlb_played_last,playerID,awardID,yearID,lgID
761,Kris Bryant,2015.0,2022.0,bryankr01,Most Valuable Player,2016,NL
5584,Giancarlo Stanton,2010.0,2022.0,stantmi03,Most Valuable Player,2017,NL
124,Jose Altuve,2011.0,2022.0,altuvjo01,Most Valuable Player,2017,AL
6423,Christian Yelich,2013.0,2022.0,yelicch01,Most Valuable Player,2018,NL
469,Mookie Betts,2014.0,2022.0,bettsmo01,Most Valuable Player,2018,AL
384,Cody Bellinger,2017.0,2022.0,bellico01,Most Valuable Player,2019,NL
5877,Mike Trout,2011.0,2022.0,troutmi01,Most Valuable Player,2019,AL
25,José Abreu,2014.0,2022.0,abreujo02,Most Valuable Player,2020,AL
1909,Freddie Freeman,2010.0,2022.0,freemfr01,Most Valuable Player,2020,NL
2478,Bryce Harper,2012.0,2022.0,harpebr03,Most Valuable Player,2021,NL
4182,Shohei Ohtani,2018.0,2022.0,ohtansh01,Most Valuable Player,2021,AL

### Merge awards and players dataframes

In [3]:
data = Merger(all_awards)
data

............Scraping Data.............

1982 Time: 1.0445339679718018 Seconds
1983 Time: 1.195610761642456 Seconds
1984 Time: 1.0407910346984863 Seconds
1985 Time: 1.0716478824615479 Seconds
1986 Time: 0.9833049774169922 Seconds

.......Approximately 57 Seconds.......

Total Time: 47.08753061294556 Seconds

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,xBA,xSLG,xwOBA,mlb_played_first,mlb_played_last,playerID,awardID,yearID,lgID,MVP
0,1014396,1982,Robin Yount,MIL,26,156,635,704,210,123,...,NaN,NaN,NaN,1974.0,1993.0,yountro01,Gold Glove,1982.0,AL,1
1,1014396,1982,Robin Yount,MIL,26,156,635,704,210,123,...,NaN,NaN,NaN,1974.0,1993.0,yountro01,Most Valuable Player,1982.0,AL,1
2,1014396,1982,Robin Yount,MIL,26,156,635,704,210,123,...,NaN,NaN,NaN,1974.0,1993.0,yountro01,Silver Slugger,1982.0,AL,1
3,1014396,1982,Robin Yount,MIL,26,156,635,704,210,123,...,NaN,NaN,NaN,1974.0,1993.0,yountro01,TSN All-Star,1982.0,AL,1
4,1014396,1982,Robin Yount,MIL,26,156,635,704,210,123,...,NaN,NaN,NaN,1974.0,1993.0,yountro01,TSN Major League Player of the Year,1982.0,AL,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,17696,2021,Kevin Newman,PIT,27,148,517,554,117,87,...,0.255,0.330,0.275,NaN,NaN,NaN,No Award,NaN,NL,0
142,14221,2021,Jorge Soler,- - -,29,149,516,602,115,61,...,0.250,0.494,0.359,2014.0,2022.0,solerjo01,World Series MVP,2021.0,ML,0
143,2396,2021,Carlos Santana,KCR,35,158,565,659,121,87,...,0.244,0.421,0.335,NaN,NaN,NaN,No Award,NaN,AL,0
144,1744,2021,Miguel Cabrera,DET,38,130,472,526,121,90,...,0.234,0.420,0.315,NaN,NaN,NaN,No Award,NaN,AL,0
145,15117,2021,Hunter Dozier,KCR,29,144,487,543,105,56,...,0.224,0.388,0.299,NaN,NaN,NaN,No Award,NaN,AL,0

In [4]:
count=0
for x in data['lgID'].isna():
    if x == True:
        count += 1      
print(str(count)+' Rows with no Team Names')
empty_league =data.loc[(data['lgID'] != 'NL') & (data['lgID'] != 'AL')]
empty_league['Team'].unique()

318 Rows with no Team Names

array(['- - -'], dtype=object)

In [5]:
print('None of these entries have an MVP')
empty_league.loc[empty_league['awardID'] == 'Most Valuable Player']

None of these entries have an MVP

Empty DataFrame
Columns: [IDfg, Season, Name, Team, Age, G, AB, PA, H, 1B, 2B, 3B, HR, R, RBI, BB, IBB, SO, HBP, SF, SH, GDP, SB, CS, AVG, GB, FB, LD, IFFB, Pitches, Balls, Strikes, IFH, BU, BUH, BB%, K%, BB/K, OBP, SLG, OPS, ISO, BABIP, GB/FB, LD%, GB%, FB%, IFFB%, HR/FB, IFH%, BUH%, wOBA, wRAA, wRC, Bat, Fld, Rep, Pos, RAR, WAR, Dol, Spd, wRC+, WPA, -WPA, +WPA, RE24, REW, pLI, phLI, PH, WPA/LI, Clutch, FB% (Pitch), FBv, SL%, SLv, CT%, CTv, CB%, CBv, CH%, CHv, SF%, SFv, KN%, KNv, XX%, PO%, wFB, wSL, wCT, wCB, wCH, wSF, wKN, wFB/C, wSL/C, wCT/C, wCB/C, ...]
Index: []

[0 rows x 326 columns]

In [6]:
print('Some have won other awards')
empty_league.loc[empty_league['awardID'] != 'No Award']

Some have won other awards

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,xBA,xSLG,xwOBA,mlb_played_first,mlb_played_last,playerID,awardID,yearID,lgID,MVP
103,2434,2021,Nelson Cruz,- - -,40,140,513,584,136,82,...,0.264,0.512,0.363,2005.0,2022.0,cruzne02,Roberto Clemente Award,2021.0,ML,0
142,14221,2021,Jorge Soler,- - -,29,149,516,602,115,61,...,0.250,0.494,0.359,2014.0,2022.0,solerjo01,World Series MVP,2021.0,ML,0
103,2434,2021,Nelson Cruz,- - -,40,140,513,584,136,82,...,0.264,0.512,0.363,2005.0,2022.0,cruzne02,Roberto Clemente Award,2021.0,ML,0
142,14221,2021,Jorge Soler,- - -,29,149,516,602,115,61,...,0.250,0.494,0.359,2014.0,2022.0,solerjo01,World Series MVP,2021.0,ML,0

### NL MVP Check

In [7]:
mvpVerify(data)

There are/is 51 unique mvps
['Robin Yount' 'Dale Murphy' 'Cal Ripken' 'Ryne Sandberg' 'Don Mattingly'
 'Mike Schmidt' 'George Bell' 'Andre Dawson' 'Jose Canseco' 'Kirk Gibson'
 'Kevin Mitchell' 'Rickey Henderson' 'Barry Bonds' 'Terry Pendleton'
 'Frank Thomas' 'Jeff Bagwell' 'Barry Larkin' 'Mo Vaughn' 'Ken Caminiti'
 'Juan Gonzalez' 'Larry Walker' 'Sammy Sosa' 'Chipper Jones'
 'Ivan Rodriguez' 'Jason Giambi' 'Jeff Kent' 'Ichiro Suzuki'
 'Miguel Tejada' 'Alex Rodriguez' 'Vladimir Guerrero' 'Albert Pujols'
 'Ryan Howard' 'Justin Morneau' 'Jimmy Rollins' 'Dustin Pedroia'
 'Joe Mauer' 'Josh Hamilton' 'Joey Votto' 'Ryan Braun' 'Buster Posey'
 'Miguel Cabrera' 'Mike Trout' 'Bryce Harper' 'Josh Donaldson'
 'Kris Bryant' 'Jose Altuve' 'Giancarlo Stanton' 'Mookie Betts'
 'Christian Yelich' 'Cody Bellinger' 'Shohei Ohtani']

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,xBA,xSLG,xwOBA,mlb_played_first,mlb_played_last,playerID,awardID,yearID,lgID,MVP
0,1014396,1982,Robin Yount,MIL,26,156,635,704,210,123,...,NaN,NaN,NaN,1974.0,1993.0,yountro01,Gold Glove,1982.0,AL,1
1,1014396,1982,Robin Yount,MIL,26,156,635,704,210,123,...,NaN,NaN,NaN,1974.0,1993.0,yountro01,Most Valuable Player,1982.0,AL,1
2,1014396,1982,Robin Yount,MIL,26,156,635,704,210,123,...,NaN,NaN,NaN,1974.0,1993.0,yountro01,Silver Slugger,1982.0,AL,1
3,1014396,1982,Robin Yount,MIL,26,156,635,704,210,123,...,NaN,NaN,NaN,1974.0,1993.0,yountro01,TSN All-Star,1982.0,AL,1
4,1014396,1982,Robin Yount,MIL,26,156,635,704,210,123,...,NaN,NaN,NaN,1974.0,1993.0,yountro01,TSN Major League Player of the Year,1982.0,AL,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,11579,2021,Bryce Harper,PHI,28,141,488,599,151,73,...,0.301,0.609,0.430,2012.0,2022.0,harpebr03,TSN All-Star,2021.0,NL,1
24,19755,2021,Shohei Ohtani,LAA,26,158,537,639,138,58,...,0.269,0.616,0.411,2018.0,2022.0,ohtansh01,Most Valuable Player,2021.0,AL,1
25,19755,2021,Shohei Ohtani,LAA,26,158,537,639,138,58,...,0.269,0.616,0.411,2018.0,2022.0,ohtansh01,Silver Slugger,2021.0,AL,1
26,19755,2021,Shohei Ohtani,LAA,26,158,537,639,138,58,...,0.269,0.616,0.411,2018.0,2022.0,ohtansh01,Outstanding DH Award,2021.0,AL,1
27,19755,2021,Shohei Ohtani,LAA,26,158,537,639,138,58,...,0.269,0.616,0.411,2018.0,2022.0,ohtansh01,TSN All-Star,2021.0,AL,1

## Export to Postgre

Make sure this connection string work:

 1) Verify connection points, and import config with variable db_password=YOUR_POSTGRE_PASSWORD
 
 2) Creating a Raw_Stats database in Postgre
 
 3) Drop 'AL' and 'NL' tables if they exist

In [10]:
engine = create_engine(f"postgresql://postgres:{db_password}@127.0.0.1:5432/Raw_Stats")

data_NL.to_sql(name='NL', con=engine)
data_AL.to_sql(name='AL', con=engine)

786