# Using cleaned_merged_df to create some specific dataframes for visualizations

In [1]:
# Importing dependacies/libraries 

from Cleaner import *

In [6]:
# Reading in cleaned_merged_df.csv as a dataframe

cleaned_merged_df = pd.read_csv('Resources/cleaned_merged_df.csv', index_col=False)
cleaned_merged_df

,Unnamed: 0,G,AB,PA,H,1B,2B,3B,HR,R,...,BsR,wSB,Off,AVG+,OBP+,SLG+,ISO+,BABIP+,MVP,XBH+
0,6,154,557,653,163,101,32,1,29,91,...,-1.6,-1.6,34.9,110,116,132,181,98,0,0.136294
1,9,148,607,659,183,116,37,7,23,107,...,3.9,3.9,30.8,114,105,129,164,112,0,0.119879
2,11,148,514,631,144,80,26,3,35,108,...,0.1,0.1,42.9,105,122,142,222,106,0,0.064976
3,16,150,575,652,175,111,27,5,32,87,...,2.4,2.4,43.2,115,115,139,192,108,0,0.095092
4,18,162,598,698,168,107,23,2,36,113,...,0.3,0.3,34.9,106,115,131,188,106,1,0.057307
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5270,136,139,457,512,112,70,28,0,14,55,...,-1.6,-0.4,-1.4,100,101,96,90,99,0,-0.021484
5271,140,149,511,545,123,75,25,1,22,59,...,-4.9,-1.6,-14.7,98,89,102,107,91,0,-0.012844
5272,143,158,565,659,121,87,15,0,19,66,...,-0.8,-0.2,-14.6,87,101,82,75,78,0,-0.003035
5273,144,130,472,526,121,90,16,0,15,48,...,-6.3,-0.5,-11.4,104,100,93,76,104,0,-0.074144
5274,145,144,487,543,105,56,27,6,16,55,...,-1.4,-1.0,-13.3,88,90,95,105,94,0,-0.092081

In [9]:
# Creating a dataframe of just the MVPs

mvps = cleaned_merged_df.loc[cleaned_merged_df['MVP'] == 1 ]
mvps

,Unnamed: 0,G,AB,PA,H,1B,2B,3B,HR,R,...,BsR,wSB,Off,AVG+,OBP+,SLG+,ISO+,BABIP+,MVP,XBH+
4,18,162,598,698,168,107,23,2,36,113,...,0.3,0.3,34.9,106,115,131,188,106,1,0.057307
66,9,162,589,687,178,114,24,4,36,131,...,4.3,4.3,44.5,115,119,138,188,110,1,0.123726
127,2,156,636,700,200,126,36,19,19,114,...,3.6,3.6,36.4,119,112,136,172,120,1,0.124286
241,15,160,552,657,160,93,29,1,37,97,...,-0.6,-0.6,35.9,111,118,139,194,97,1,0.121766
305,67,153,621,662,178,103,24,2,49,90,...,0.7,0.7,20.9,107,97,136,188,93,1,0.093656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4934,0,159,549,681,173,107,32,5,29,123,...,9.6,2.6,67.0,122,137,130,141,124,1,0.076358
5009,3,153,590,662,204,137,39,4,24,112,...,4.0,3.4,52.7,135,126,127,116,124,1,0.143505
5081,0,136,520,614,180,96,47,5,32,129,...,6.9,3.1,69.3,139,137,154,176,125,1,0.198697
5148,0,134,470,600,137,63,27,2,45,110,...,7.1,0.9,65.9,115,136,146,190,100,1,0.106667
5218,24,158,537,639,138,58,26,8,46,103,...,2.5,0.5,42.9,104,118,142,197,104,1,-0.009390

In [14]:
# Drop Unnamed: 0 column 

mvps.drop(columns= 'Unnamed: 0')

,G,AB,PA,H,1B,2B,3B,HR,R,RBI,...,BsR,wSB,Off,AVG+,OBP+,SLG+,ISO+,BABIP+,MVP,XBH+
4,162,598,698,168,107,23,2,36,113,109,...,0.3,0.3,34.9,106,115,131,188,106,1,0.057307
66,162,589,687,178,114,24,4,36,131,121,...,4.3,4.3,44.5,115,119,138,188,110,1,0.123726
127,156,636,700,200,126,36,19,19,114,84,...,3.6,3.6,36.4,119,112,136,172,120,1,0.124286
241,160,552,657,160,93,29,1,37,97,119,...,-0.6,-0.6,35.9,111,118,139,194,97,1,0.121766
305,153,621,662,178,103,24,2,49,90,137,...,0.7,0.7,20.9,107,97,136,188,93,1,0.093656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4934,159,549,681,173,107,32,5,29,123,100,...,9.6,2.6,67.0,122,137,130,141,124,1,0.076358
5009,153,590,662,204,137,39,4,24,112,81,...,4.0,3.4,52.7,135,126,127,116,124,1,0.143505
5081,136,520,614,180,96,47,5,32,129,80,...,6.9,3.1,69.3,139,137,154,176,125,1,0.198697
5148,134,470,600,137,63,27,2,45,110,104,...,7.1,0.9,65.9,115,136,146,190,100,1,0.106667
5218,158,537,639,138,58,26,8,46,103,100,...,2.5,0.5,42.9,104,118,142,197,104,1,-0.009390

In [21]:
# Isolating a handful of stats that I deem most important/impactful 

mvps_important_stats = mvps[['H','RBI','AVG','OBP','SLG','OPS','ISO']]
mvps_important_stats

        H  RBI    AVG    OBP    SLG    OPS    ISO
4     168  109  0.281  0.378  0.507  0.885  0.226
66    178  121  0.302  0.393  0.540  0.933  0.238
127   200   84  0.314  0.367  0.520  0.887  0.206
241   160  119  0.290  0.390  0.547  0.937  0.257
305   178  137  0.287  0.328  0.568  0.896  0.282
...   ...  ...    ...    ...    ...    ...    ...
4934  173  100  0.315  0.441  0.550  0.991  0.235
5009  204   81  0.346  0.410  0.547  0.957  0.202
5081  180   80  0.346  0.438  0.640  1.078  0.294
5148  137  104  0.291  0.438  0.645  1.083  0.353
5218  138  100  0.257  0.372  0.592  0.965  0.335

[70 rows x 7 columns]

In [22]:
# Get summmary statistics 

mvps_important_stats.describe()

,H,RBI,AVG,OBP,SLG,OPS,ISO
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,179.957143,113.814286,0.320829,0.412257,0.604443,1.016757,0.283686
std,22.121165,21.741094,0.023357,0.050612,0.076511,0.120553,0.069438
min,133.000000,61.000000,0.257000,0.328000,0.457000,0.838000,0.107000
25%,168.000000,101.000000,0.307250,0.377000,0.558250,0.939000,0.239250
50%,181.000000,114.000000,0.320000,0.399500,0.599000,0.999500,0.276500
75%,194.750000,130.000000,0.332750,0.438750,0.639000,1.072250,0.322750
max,242.000000,158.000000,0.370000,0.609000,0.863000,1.422000,0.536000

In [26]:
# Repeat this process to create the same dataframe for non-MVP players

# Creating a dataframe of non-MVPs

non_mvps = cleaned_merged_df.loc[cleaned_merged_df['MVP'] == 0 ]
non_mvps

,Unnamed: 0,G,AB,PA,H,1B,2B,3B,HR,R,...,BsR,wSB,Off,AVG+,OBP+,SLG+,ISO+,BABIP+,MVP,XBH+
0,6,154,557,653,163,101,32,1,29,91,...,-1.6,-1.6,34.9,110,116,132,181,98,0,0.136294
1,9,148,607,659,183,116,37,7,23,107,...,3.9,3.9,30.8,114,105,129,164,112,0,0.119879
2,11,148,514,631,144,80,26,3,35,108,...,0.1,0.1,42.9,105,122,142,222,106,0,0.064976
3,16,150,575,652,175,111,27,5,32,87,...,2.4,2.4,43.2,115,115,139,192,108,0,0.095092
5,29,154,568,634,181,126,33,3,19,92,...,1.2,1.2,25.1,120,112,126,141,107,0,0.170347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5270,136,139,457,512,112,70,28,0,14,55,...,-1.6,-0.4,-1.4,100,101,96,90,99,0,-0.021484
5271,140,149,511,545,123,75,25,1,22,59,...,-4.9,-1.6,-14.7,98,89,102,107,91,0,-0.012844
5272,143,158,565,659,121,87,15,0,19,66,...,-0.8,-0.2,-14.6,87,101,82,75,78,0,-0.003035
5273,144,130,472,526,121,90,16,0,15,48,...,-6.3,-0.5,-11.4,104,100,93,76,104,0,-0.074144
5274,145,144,487,543,105,56,27,6,16,55,...,-1.4,-1.0,-13.3,88,90,95,105,94,0,-0.092081

In [30]:
# Drop Unnamed: 0 column 

non_mvps.drop(columns= 'Unnamed: 0')

,G,AB,PA,H,1B,2B,3B,HR,R,RBI,...,BsR,wSB,Off,AVG+,OBP+,SLG+,ISO+,BABIP+,MVP,XBH+
0,154,557,653,163,101,32,1,29,91,97,...,-1.6,-1.6,34.9,110,116,132,181,98,0,0.136294
1,148,607,659,183,116,37,7,23,107,83,...,3.9,3.9,30.8,114,105,129,164,112,0,0.119879
2,148,514,631,144,80,26,3,35,108,87,...,0.1,0.1,42.9,105,122,142,222,106,0,0.064976
3,150,575,652,175,111,27,5,32,87,100,...,2.4,2.4,43.2,115,115,139,192,108,0,0.095092
5,154,568,634,181,126,33,3,19,92,95,...,1.2,1.2,25.1,120,112,126,141,107,0,0.170347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5270,139,457,512,112,70,28,0,14,55,69,...,-1.6,-0.4,-1.4,100,101,96,90,99,0,-0.021484
5271,149,511,545,123,75,25,1,22,59,81,...,-4.9,-1.6,-14.7,98,89,102,107,91,0,-0.012844
5272,158,565,659,121,87,15,0,19,66,69,...,-0.8,-0.2,-14.6,87,101,82,75,78,0,-0.003035
5273,130,472,526,121,90,16,0,15,48,75,...,-6.3,-0.5,-11.4,104,100,93,76,104,0,-0.074144
5274,144,487,543,105,56,27,6,16,55,54,...,-1.4,-1.0,-13.3,88,90,95,105,94,0,-0.092081

In [33]:
# Isolating a handful of stats that I deem most important/impactful 

non_mvps_important_stats = non_mvps[['H','RBI','AVG','OBP','SLG','OPS','ISO']]
non_mvps_important_stats

        H  RBI    AVG    OBP    SLG    OPS    ISO
0     163   97  0.293  0.381  0.510  0.890  0.217
1     183   83  0.301  0.344  0.499  0.843  0.198
2     144   87  0.280  0.403  0.547  0.949  0.267
3     175  100  0.304  0.378  0.536  0.914  0.231
5     181   95  0.319  0.368  0.488  0.856  0.169
...   ...  ...    ...    ...    ...    ...    ...
5270  112   69  0.245  0.318  0.398  0.717  0.153
5271  123   81  0.241  0.281  0.423  0.703  0.182
5272  121   69  0.214  0.319  0.342  0.660  0.127
5273  121   75  0.256  0.316  0.386  0.701  0.129
5274  105   54  0.216  0.285  0.394  0.680  0.179

[5205 rows x 7 columns]

In [34]:
# Get summmary statistics 

non_mvps_important_stats.describe()

,H,RBI,AVG,OBP,SLG,OPS,ISO
count,5205.000000,5205.000000,5205.000000,5205.000000,5205.000000,5205.000000,5205.000000
mean,149.308934,75.049952,0.277248,0.347128,0.446984,0.794111,0.169743
std,25.162375,23.736168,0.027166,0.035473,0.070457,0.096470,0.060330
min,69.000000,17.000000,0.168000,0.228000,0.258000,0.518000,0.023000
25%,131.000000,57.000000,0.258000,0.322000,0.397000,0.726000,0.126000
50%,148.000000,74.000000,0.276000,0.346000,0.443000,0.787000,0.167000
75%,166.000000,91.000000,0.295000,0.369000,0.491000,0.854000,0.211000
max,262.000000,165.000000,0.394000,0.479000,0.752000,1.222000,0.454000

In [35]:
# Saving each new dataframe to be used in Tableau 

mvps_important_stats.to_csv('Resources/mvps_stats.csv')
non_mvps_important_stats.to_csv('Resources/non_mvps_stats.csv')