In [1]:
# The purose of this notebook is to clean, organize, and explore the data set 
# before determining the most important features for our machine learning model.

In [2]:
# Import packages and libraries

from pybaseball import batting_stats_range
from pybaseball import batting_stats
from pathlib import Path
import numpy as np
import pandas as pd

In [3]:
# Gathering batting stats from 2015

data = batting_stats(2015)

batting_df = pd.DataFrame(data)
batting_df.head()

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,Barrel%,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA
0,11579,2015,Bryce Harper,WSN,22,153,521,654,172,91,...,0.122,116.0,188,0.477,394,0.118,0.226,0.292,0.544,0.418
3,10155,2015,Mike Trout,LAA,23,159,575,682,172,93,...,0.161,117.7,205,0.486,422,0.207,0.282,0.297,0.588,0.422
5,5038,2015,Josh Donaldson,TOR,29,158,620,711,184,100,...,0.114,113.6,232,0.465,499,0.145,0.255,0.280,0.546,0.390
1,4314,2015,Joey Votto,CIN,31,158,545,695,171,107,...,0.095,109.3,175,0.425,412,0.177,0.254,0.289,0.541,0.422
2,9218,2015,Paul Goldschmidt,ARI,27,159,567,695,182,109,...,0.123,114.0,197,0.465,424,0.181,0.266,0.279,0.558,0.403

In [4]:
len(data)

141

In [5]:
# Dropped all columns with NaN values 

batting_df = batting_df.dropna(axis=1)
batting_df

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,Barrel%,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA
0,11579,2015,Bryce Harper,WSN,22,153,521,654,172,91,...,0.122,116.0,188,0.477,394,0.118,0.226,0.292,0.544,0.418
3,10155,2015,Mike Trout,LAA,23,159,575,682,172,93,...,0.161,117.7,205,0.486,422,0.207,0.282,0.297,0.588,0.422
5,5038,2015,Josh Donaldson,TOR,29,158,620,711,184,100,...,0.114,113.6,232,0.465,499,0.145,0.255,0.280,0.546,0.390
1,4314,2015,Joey Votto,CIN,31,158,545,695,171,107,...,0.095,109.3,175,0.425,412,0.177,0.254,0.289,0.541,0.422
2,9218,2015,Paul Goldschmidt,ARI,27,159,567,695,182,109,...,0.123,114.0,197,0.465,424,0.181,0.266,0.279,0.558,0.403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,5760,2015,Avisail Garcia,CHW,24,148,553,601,142,110,...,0.043,116.1,156,0.375,416,0.095,0.268,0.271,0.409,0.324
139,1433,2015,Wilson Ramos,WSN,27,128,475,504,109,78,...,0.058,114.2,170,0.445,382,0.127,0.248,0.250,0.410,0.300
97,7399,2015,Billy Butler,OAK,29,151,538,601,135,91,...,0.070,110.0,177,0.401,441,0.194,0.273,0.249,0.441,0.335
140,10030,2015,Chris Owings,ARI,23,147,515,552,117,81,...,0.026,107.6,95,0.249,381,0.161,0.288,0.227,0.325,0.261
128,5409,2015,Pablo Sandoval,BOS,28,126,470,505,115,79,...,0.045,114.0,133,0.333,400,0.108,0.210,0.227,0.352,0.279

In [6]:
batting_df = batting_df.drop(columns= ['IDfg','Season','Team','Age'])
batting_df

,Name,G,AB,PA,H,1B,2B,3B,HR,R,...,Barrel%,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA
0,Bryce Harper,153,521,654,172,91,38,1,42,118,...,0.122,116.0,188,0.477,394,0.118,0.226,0.292,0.544,0.418
3,Mike Trout,159,575,682,172,93,32,6,41,104,...,0.161,117.7,205,0.486,422,0.207,0.282,0.297,0.588,0.422
5,Josh Donaldson,158,620,711,184,100,41,2,41,122,...,0.114,113.6,232,0.465,499,0.145,0.255,0.280,0.546,0.390
1,Joey Votto,158,545,695,171,107,33,2,29,95,...,0.095,109.3,175,0.425,412,0.177,0.254,0.289,0.541,0.422
2,Paul Goldschmidt,159,567,695,182,109,38,2,33,103,...,0.123,114.0,197,0.465,424,0.181,0.266,0.279,0.558,0.403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,Avisail Garcia,148,553,601,142,110,17,2,13,66,...,0.043,116.1,156,0.375,416,0.095,0.268,0.271,0.409,0.324
139,Wilson Ramos,128,475,504,109,78,16,0,15,41,...,0.058,114.2,170,0.445,382,0.127,0.248,0.250,0.410,0.300
97,Billy Butler,151,538,601,135,91,28,1,15,63,...,0.070,110.0,177,0.401,441,0.194,0.273,0.249,0.441,0.335
140,Chris Owings,147,515,552,117,81,27,5,4,59,...,0.026,107.6,95,0.249,381,0.161,0.288,0.227,0.325,0.261
128,Pablo Sandoval,126,470,505,115,79,25,1,10,43,...,0.045,114.0,133,0.333,400,0.108,0.210,0.227,0.352,0.279

In [7]:
batting_df.describe()

,G,AB,PA,H,1B,2B,3B,HR,R,RBI,...,Barrel%,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA
count,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,...,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000
mean,147.397163,545.234043,605.929078,148.631206,97.943262,29.092199,3.106383,18.489362,74.297872,71.439716,...,0.055532,110.951064,156.241135,0.357064,441.489362,0.164043,0.255943,0.260830,0.422894,0.328674
std,10.181832,52.314111,60.458090,22.256752,21.314909,6.905382,2.526155,10.325154,16.943918,20.070721,...,0.035782,2.925519,35.527032,0.078157,59.102165,0.033089,0.024721,0.021778,0.070307,0.038348
min,116.000000,429.000000,503.000000,101.000000,54.000000,14.000000,0.000000,2.000000,34.000000,26.000000,...,0.000000,104.000000,63.000000,0.142000,314.000000,0.091000,0.188000,0.204000,0.288000,0.258000
25%,141.000000,505.000000,553.000000,133.000000,81.000000,24.000000,1.000000,11.000000,63.000000,56.000000,...,0.028000,108.900000,135.000000,0.311000,400.000000,0.141000,0.239000,0.245000,0.371000,0.302000
50%,151.000000,549.000000,612.000000,147.000000,98.000000,29.000000,2.000000,17.000000,73.000000,71.000000,...,0.047000,110.600000,156.000000,0.363000,442.000000,0.164000,0.256000,0.261000,0.416000,0.325000
75%,156.000000,586.000000,657.000000,165.000000,111.000000,34.000000,5.000000,23.000000,85.000000,84.000000,...,0.077000,113.200000,179.000000,0.407000,481.000000,0.185000,0.276000,0.276000,0.466000,0.350000
max,162.000000,638.000000,713.000000,205.000000,169.000000,45.000000,12.000000,47.000000,122.000000,130.000000,...,0.168000,119.000000,238.000000,0.527000,580.000000,0.248000,0.305000,0.323000,0.616000,0.432000

In [8]:
# Adding a 'MVP' column

batting_df["MVP"] = "np.NaT"
batting_df

,Name,G,AB,PA,H,1B,2B,3B,HR,R,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,MVP
0,Bryce Harper,153,521,654,172,91,38,1,42,118,...,116.0,188,0.477,394,0.118,0.226,0.292,0.544,0.418,np.NaT
3,Mike Trout,159,575,682,172,93,32,6,41,104,...,117.7,205,0.486,422,0.207,0.282,0.297,0.588,0.422,np.NaT
5,Josh Donaldson,158,620,711,184,100,41,2,41,122,...,113.6,232,0.465,499,0.145,0.255,0.280,0.546,0.390,np.NaT
1,Joey Votto,158,545,695,171,107,33,2,29,95,...,109.3,175,0.425,412,0.177,0.254,0.289,0.541,0.422,np.NaT
2,Paul Goldschmidt,159,567,695,182,109,38,2,33,103,...,114.0,197,0.465,424,0.181,0.266,0.279,0.558,0.403,np.NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,Avisail Garcia,148,553,601,142,110,17,2,13,66,...,116.1,156,0.375,416,0.095,0.268,0.271,0.409,0.324,np.NaT
139,Wilson Ramos,128,475,504,109,78,16,0,15,41,...,114.2,170,0.445,382,0.127,0.248,0.250,0.410,0.300,np.NaT
97,Billy Butler,151,538,601,135,91,28,1,15,63,...,110.0,177,0.401,441,0.194,0.273,0.249,0.441,0.335,np.NaT
140,Chris Owings,147,515,552,117,81,27,5,4,59,...,107.6,95,0.249,381,0.161,0.288,0.227,0.325,0.261,np.NaT
128,Pablo Sandoval,126,470,505,115,79,25,1,10,43,...,114.0,133,0.333,400,0.108,0.210,0.227,0.352,0.279,np.NaT

In [9]:
# Changing the values in the 'MVP' column to '0'.

batting_df['MVP'] = 0
batting_df.head()

,Name,G,AB,PA,H,1B,2B,3B,HR,R,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,MVP
0,Bryce Harper,153,521,654,172,91,38,1,42,118,...,116.0,188,0.477,394,0.118,0.226,0.292,0.544,0.418,0
3,Mike Trout,159,575,682,172,93,32,6,41,104,...,117.7,205,0.486,422,0.207,0.282,0.297,0.588,0.422,0
5,Josh Donaldson,158,620,711,184,100,41,2,41,122,...,113.6,232,0.465,499,0.145,0.255,0.280,0.546,0.390,0
1,Joey Votto,158,545,695,171,107,33,2,29,95,...,109.3,175,0.425,412,0.177,0.254,0.289,0.541,0.422,0
2,Paul Goldschmidt,159,567,695,182,109,38,2,33,103,...,114.0,197,0.465,424,0.181,0.266,0.279,0.558,0.403,0

In [10]:
# This dataset is for the year 2015. Josh Donaldson won MVP that year - assigning a '1' to his 'MVP' column.

batting_df.at[5, 'MVP']=1
batting_df.head()

,Name,G,AB,PA,H,1B,2B,3B,HR,R,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,MVP
0,Bryce Harper,153,521,654,172,91,38,1,42,118,...,116.0,188,0.477,394,0.118,0.226,0.292,0.544,0.418,0
3,Mike Trout,159,575,682,172,93,32,6,41,104,...,117.7,205,0.486,422,0.207,0.282,0.297,0.588,0.422,0
5,Josh Donaldson,158,620,711,184,100,41,2,41,122,...,113.6,232,0.465,499,0.145,0.255,0.280,0.546,0.390,1
1,Joey Votto,158,545,695,171,107,33,2,29,95,...,109.3,175,0.425,412,0.177,0.254,0.289,0.541,0.422,0
2,Paul Goldschmidt,159,567,695,182,109,38,2,33,103,...,114.0,197,0.465,424,0.181,0.266,0.279,0.558,0.403,0

In [11]:
list(batting_df.columns)

['Name',
 'G',
 'AB',
 'PA',
 'H',
 '1B',
 '2B',
 '3B',
 'HR',
 'R',
 'RBI',
 'BB',
 'IBB',
 'SO',
 'HBP',
 'SF',
 'SH',
 'GDP',
 'SB',
 'CS',
 'AVG',
 'GB',
 'FB',
 'LD',
 'IFFB',
 'Pitches',
 'Balls',
 'Strikes',
 'IFH',
 'BU',
 'BUH',
 'BB%',
 'K%',
 'BB/K',
 'OBP',
 'SLG',
 'OPS',
 'ISO',
 'BABIP',
 'GB/FB',
 'LD%',
 'GB%',
 'FB%',
 'IFFB%',
 'HR/FB',
 'IFH%',
 'BUH%',
 'wOBA',
 'wRAA',
 'wRC',
 'Bat',
 'Fld',
 'Rep',
 'Pos',
 'RAR',
 'WAR',
 'Dol',
 'Spd',
 'wRC+',
 'WPA',
 '-WPA',
 '+WPA',
 'RE24',
 'REW',
 'pLI',
 'PH',
 'WPA/LI',
 'Clutch',
 'FB% (Pitch)',
 'FBv',
 'SL%',
 'SLv',
 'CT%',
 'CTv',
 'CB%',
 'CBv',
 'CH%',
 'CHv',
 'SF%',
 'SFv',
 'wFB',
 'wSL',
 'wCT',
 'wCB',
 'wCH',
 'wSF',
 'wFB/C',
 'wSL/C',
 'wCT/C',
 'wCB/C',
 'wCH/C',
 'wSF/C',
 'O-Swing%',
 'Z-Swing%',
 'Swing%',
 'O-Contact%',
 'Z-Contact%',
 'Contact%',
 'Zone%',
 'F-Strike%',
 'SwStr%',
 'BsR',
 'FA% (sc)',
 'FT% (sc)',
 'FC% (sc)',
 'FS% (sc)',
 'SI% (sc)',
 'SL% (sc)',
 'CU% (sc)',
 'KC% (sc)',
 'CH% (sc)',
 'vFA (sc)',
 'vFT (sc)',
 'vFC (sc)',
 'vFS (sc)',
 'vSI (sc)',
 'vSL (sc)',
 'vCU (sc)',
 'vKC (sc)',
 'vCH (sc)',
 'FA-X (sc)',
 'FT-X (sc)',
 'FC-X (sc)',
 'FS-X (sc)',
 'SI-X (sc)',
 'SL-X (sc)',
 'CU-X (sc)',
 'KC-X (sc)',
 'CH-X (sc)',
 'FA-Z (sc)',
 'FT-Z (sc)',
 'FC-Z (sc)',
 'FS-Z (sc)',
 'SI-Z (sc)',
 'SL-Z (sc)',
 'CU-Z (sc)',
 'KC-Z (sc)',
 'CH-Z (sc)',
 'wFA (sc)',
 'wFT (sc)',
 'wFC (sc)',
 'wFS (sc)',
 'wSI (sc)',
 'wSL (sc)',
 'wCU (sc)',
 'wKC (sc)',
 'wCH (sc)',
 'wFA/C (sc)',
 'wFT/C (sc)',
 'wFC/C (sc)',
 'wFS/C (sc)',
 'wSI/C (sc)',
 'wSL/C (sc)',
 'wCU/C (sc)',
 'wKC/C (sc)',
 'wCH/C (sc)',
 'O-Swing% (sc)',
 'Z-Swing% (sc)',
 'Swing% (sc)',
 'O-Contact% (sc)',
 'Z-Contact% (sc)',
 'Contact% (sc)',
 'Zone% (sc)',
 'Pace',
 'Def',
 'wSB',
 'UBR',
 'Age Rng',
 'Off',
 'Lg',
 'wGDP',
 'Pull%',
 'Cent%',
 'Oppo%',
 'Soft%',
 'Med%',
 'Hard%',
 'TTO%',
 'CH% (pi)',
 'CU% (pi)',
 'FA% (pi)',
 'FC% (pi)',
 'FS% (pi)',
 'SI% (pi)',
 'SL% (pi)',
 'vCH (pi)',
 'vCU (pi)',
 'vFA (pi)',
 'vFC (pi)',
 'vFS (pi)',
 'vSI (pi)',
 'vSL (pi)',
 'CH-X (pi)',
 'CU-X (pi)',
 'FA-X (pi)',
 'FC-X (pi)',
 'FS-X (pi)',
 'SI-X (pi)',
 'SL-X (pi)',
 'CH-Z (pi)',
 'CU-Z (pi)',
 'FA-Z (pi)',
 'FC-Z (pi)',
 'FS-Z (pi)',
 'SI-Z (pi)',
 'SL-Z (pi)',
 'wCH (pi)',
 'wCU (pi)',
 'wFA (pi)',
 'wFC (pi)',
 'wFS (pi)',
 'wSI (pi)',
 'wSL (pi)',
 'wCH/C (pi)',
 'wCU/C (pi)',
 'wFA/C (pi)',
 'wFC/C (pi)',
 'wFS/C (pi)',
 'wSI/C (pi)',
 'wSL/C (pi)',
 'O-Swing% (pi)',
 'Z-Swing% (pi)',
 'Swing% (pi)',
 'O-Contact% (pi)',
 'Z-Contact% (pi)',
 'Contact% (pi)',
 'Zone% (pi)',
 'Pace (pi)',
 'AVG+',
 'BB%+',
 'K%+',
 'OBP+',
 'SLG+',
 'ISO+',
 'BABIP+',
 'LD+%',
 'GB%+',
 'FB%+',
 'HR/FB%+',
 'Pull%+',
 'Cent%+',
 'Oppo%+',
 'Soft%+',
 'Med%+',
 'Hard%+',
 'EV',
 'LA',
 'Barrels',
 'Barrel%',
 'maxEV',
 'HardHit',
 'HardHit%',
 'Events',
 'CStr%',
 'CSW%',
 'xBA',
 'xSLG',
 'xwOBA',
 'MVP']

In [12]:
batting_df = batting_df[['Name',
 'G',
 'AB',
 'PA',
 'H',
 '1B',
 '2B',
 '3B',
 'HR',
 'R',
 'RBI',
 'BB',
 'IBB',
 'SO',
 'HBP',
 'SF',
 'SH',
 'GDP',
 'SB',
 'CS',
 'AVG',
 'GB',
 'FB',
 'LD',
 'IFFB',
 'Pitches',
 'Balls',
 'Strikes',
 'IFH',
 'BU',
 'BUH',
 'BB%',
 'K%',
 'BB/K',
 'OBP',
 'SLG',
 'OPS',
 'ISO',
 'BABIP',
 'GB/FB',
 'LD%',
 'GB%',
 'FB%',
 'IFFB%',
 'HR/FB',
 'IFH%',
 'BUH%',
 'wOBA',
 'wRAA',
 'wRC',
 'Bat',
 'Fld',
 'Rep',
 'Pos',
 'RAR',
 'WAR',
 'MVP']]

batting_df.head()

,Name,G,AB,PA,H,1B,2B,3B,HR,R,...,wOBA,wRAA,wRC,Bat,Fld,Rep,Pos,RAR,WAR,MVP
0,Bryce Harper,153,521,654,172,91,38,1,42,118,...,0.461,77.3,151,74.1,-4.0,19.1,-6.1,87.8,9.3,0
3,Mike Trout,159,575,682,172,93,32,6,41,104,...,0.415,55.4,132,55.7,4.7,19.9,1.9,87.6,9.3,0
5,Josh Donaldson,158,620,711,184,100,41,2,41,122,...,0.398,47.9,128,44.7,8.6,20.8,1.5,82.1,8.7,1
1,Joey Votto,158,545,695,171,107,33,2,29,95,...,0.427,63.1,141,59.8,0.0,20.3,-11.8,68.3,7.3,0
2,Paul Goldschmidt,159,567,695,182,109,38,2,33,103,...,0.418,57.9,136,51.1,4.6,20.3,-12.1,68.1,7.2,0

In [13]:
list(batting_df.dtypes)

[dtype('O'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64')]

In [14]:
# Converting batting_df into a CSV and saving to branch/repository 

batting_df.to_csv('batting_df.csv')